name       : perl-pdf-builder
version    : '3.025'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/P/PM/PMPERRY/PDF-Builder-3.025.tar.gz : a9beb4efa0ec2975a9145cef052118b2098f46d9c1510dd65786a03d0da3e3d5
homepage   : https://metacpan.org/pod/PDF::Builder
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : PDF::Builder - Facilitates the creation and modification of PDF files
description: |
    Represents a page of output in PDF. It also keeps track of the content stream, any resources (such as fonts) being switched, etc. Page inherits from Pages due to a number of shared methods. They are really structurally quite different.
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
