name       : perl-pdf-builder
version    : 3.021
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/P/PM/PMPERRY/PDF-Builder-3.021.tar.gz : 237db2ffb2d1aeaaa710c477ccae31ff70f61b67a3c7eabc2df9eaf68a1682c1
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : PDF::Builder::Basic::PDF::Page - Represents a PDF page, inherits from PDF::Builder::Basic::PDF::Pages
description: |
    Represents a page of output in PDF. It also keeps track of the content stream, any resources (such as fonts) being switched, etc. Page inherits from Pages due to a number of shared methods. They are really structurally quite different.
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
